# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f9125fc325f9c21e0a47c8651408c6cb9e81062a5b546a919897409f25e1f88669eff7a3d89be16557a33662493158887d92a815a7db5451264d20453b467c

test:
  secret_key_base: 8dfe99668f39f2b96192983188292ce9883b9b597be9ace5dff6fb5aa9834a86ce16a8ef326c51e852cf0be0275f832032eef808a9a4c32da3924a71206d9a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
